# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

name: "Release new version on Ansible Galaxy"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
      - name: "galaxy"
        uses: "robertdebock/galaxy-action@1.2.0"
        with:
          galaxy_api_key: "${{ secrets.galaxy_api_key }}"
          git_branch: "main"
